test-debian-buster-GCC8-<SOME_NAME>:
  image: gitdocker.physik.hu-berlin.de/sol/exciting:debian-buster-GCC8
  stage: test
  tags:
    - docker
  before_script:
    - apt-get --allow-releaseinfo-change update && apt-get install -y libpython3.7 libpython3.7-dev python3-pip
    - pip3 install --upgrade --force pillow==7.0.0 numpy termcolor lxml pytest pyyaml
  script:
    - pip3 install -e tools/exciting_tools
    # Run unit tests for test framework functions
    - cd <dir_name> && pytest <test_dr>
